# Generated by Django 2.0.4 on 2018-08-04 03:58

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情')),
                ('click_nums', models.IntegerField(default=0, verbose_name='文章点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='文章收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最近一次修改时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('accept_nums', models.IntegerField(default=0, verbose_name='采纳数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_content', models.TextField(verbose_name='回复讨论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='讨论时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='文章回复')),
            ],
            options={
                'verbose_name': '回复讨论',
                'verbose_name_plural': '回复讨论',
            },
        ),
    ]
