# Generated by Django 2.0.4 on 2018-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180804_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article/ueditor/', verbose_name='文章附件'),
        ),
    ]
