# -*- coding: utf-8 -*-
# @Time : 2022/1/23 0023 22:58
# @Author : Bobby_Liukeling
# @File : get_part.py

from Bio.PDB.PDBParser import PDBParser
import pdb,copy,os,warnings
import linecache

warnings.filterwarnings("ignore")


def get_resname(string): #传入一行数据
    temp = string.strip().split(' ')
    while '' in temp:
        temp.remove('')
    res_name = temp[1]
    if len(res_name) > 1:
        pass
    else:
        res_name = temp[2]
    return res_name


def get_resnames(pdb_file):
    key = "HETNAM"
    f = open(pdb_file, "r+")
    res_names = []
    guard = 0
    for line in f:
        if line.startswith(key):
            while key in line:
                res_names.append(get_resname(line))
                line = next(f)
            guard = 1
        if guard == 1:
            break
    return set(res_names).difference(del_resname)  #返回残基名字列表,只要那些可能存在的
    # return set(res_names)  #返回残基名字列表,只要那些可能存在的


#
# def get_resPDBfile(positions,pdb_filename,resname,chain,file):
#     head = """MODEL        1
# COMPND    4XEY_1N1_B_601
# AUTHOR    GENERATED BY OPEN BABEL 3.1.0"""
#
#
#     with open(pdb_filename,"w") as f:
#         f.write(head+'\n')
#         count = 2438  #原子序号
#         for i in positions:
#             # pdb.set_trace()
#             # bfactor = i.bfactor
#             # fullname = i.fullname
#             # occupancy = i.occupancy
#             coord = str(i.coord[0]) + ' '+str(i.coord[1]) + ' ' +str(i.coord[2])
#             # string = 'HETATM    {}  {}   {}     1     {}  1.00  0.00           {}\n'.format(count,i.element,resname,coord,i.element)
#             string = 'HETATM {}  {}   {} {} 101      {}   {}  {}  {} {}           {}\n'.format(count,i.fullname,resname,chain,str(i.coord[0]),str(i.coord[1]),str(i.coord[2]),i.occupancy,i.bfactor,i.element)
#             # string =
#             # string = 'HETATM 2039  N   PTR C 101      41.838   6.994  23.774  1.00 28.73           N'
#             # string = 'HETATM    {}  {}   {}     1     {}  1.00  0.00           {}\n'.format(count,i.element,resname,coord,i.element)
#             f.write(string)
#             count = count+1
#         f.write("END")
#         f.close()






pwd = os.path.dirname(os.path.realpath(__file__)) #当前文件夹下
pdb_All = pwd+"\\temp"
# pdb_All = pwd+"\\PDB_File"
files = os.listdir(pdb_All) #得到文件夹下的所有文件名称
os.chdir(pdb_All)  # 跳转到当前文件夹下
# pdb_file = "6GGC.pdb"
del_resname = ["ZN","EDO","GOL","MG","ACE","GLZ","CA","EOH","GLC","AU","CL","NI","CA"]
parser = PDBParser()
count = 0
print("*****************start*******************")
# file = "6njs.pdb"
for file in files: #遍历文件夹
    # print(file)
    try:
        structure = parser.get_structure("6GGC", file)
    except Exception as e:
        print(file)
    residues = structure.get_residues()
    residues_list = []
    resnames = get_resnames(
        file
    )
    if len(resnames) == 0: #没有配体
        continue
    length = 0

    resname = ''

    for residue in residues:
        if residue.resname in resnames:
            if length<len(residue.child_list): #原子数最多的那个残基
                length = len(residue.child_list)
                resname = residue.resname
    pdb_filename = pwd+"\\res_PDB_file\\"+file.split('.')[0] +"_"+ resname+".pdb"

    head = """MODEL        1
COMPND    4XEY_1N1_B_601 
AUTHOR    GENERATED BY OPEN BABEL 3.1.0"""

    f_new = open(pdb_filename, "w")
    f_new.write(head + '\n')

    f_old = open(file,'r+')
    # lines = f_old.readlines()
    for line in f_old:
        # pdb.set_trace()
        if resname in line:
            if "HETATM" in line:
                while ("HETATM" in line) & (resname in line):
                    f_new.write(line)
                    line = next(f_old)
                break
    f_new.write("END")


    # get_resPDBfile(positions,pdb_filename,resname,chain,file)

    if count%50 == 0:
        print("the count is : ",count)
    count = count+1

