# Generated by Django 2.0.4 on 2018-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180807_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rand',
            field=models.CharField(choices=[('1', '第一级'), ('2', '第二级'), ('3', '第三级')], default='1', max_length=10, verbose_name='用户等级'),
        ),
    ]
