
from rdkit.Chem import AllChem

resultpath = 'atom.txt'
import pdb
# atom  = []
#
# with open(resultpath,'rb') as f:
#     for line in f.readlines():  # 打开后逐行读取
#         try:
#             temp = line.decode().split("；")[-2].split("：")[-1]
#             atom.append(temp)
#         except Exception as e:
#             print(e)
#             pass

mol = AllChem.MolFromPDBFile('test2.pdb')
# 获取原子顶点属性
# atom_feature = []
# pos = []  # 原子坐标信息
atoms = {}
for atom in mol.GetAtoms():
    atoms[atom.GetSymbol()] = atom.GetAtomicNum()  # 原子编号,编码为颜色

print(atoms)




# string1 = 'COMPND'
# string2 = 'AUTHOR    GENERATED BY OPEN BABEL 3.1.0'
# string3 = 'END'
# f = open('test2.txt','a')
# f.write(string1+'\n')
# f.write(string2+'\n')
# for i in atom:
#     # pdb.set_trace()
#     f.write('HETATM    4  {}   UNL     1      -0.959   1.764   0.017  1.00  0.00           {}'.format(i,i) + '\n')
#
# f.write(string3+'\n')