"""
Django settings for Zhicheng project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os,sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))#将app添加到文件路径



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c%w)uo2!z#j(yt+^bgv+e%k)3uep5gqmx8wu!+7dq8-wm+y*a!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'articles',
    'xadmin',
    'crispy_forms',
    'DjangoUeditor',
    'captcha',#验证码
    'rest_framework',
    'rest_framework.authtoken',

]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Zhicheng.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Zhicheng.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "zhicheng",
        'USER': "root",
        'PASSWORD': "520lkl",
        'HOST': "127.0.0.1",
        'PORT': "3306",
        # 'OPTIONS': {'init_command': 'SET storage_engine=INNODB;'}
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'


# 时区改为上海
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# 数据库存储使用时间，True时间会被存为UTC的时间
USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    '127.0.0.1:8080',  # 请求的域名
    'localhost:8080',
    'localhost',
)
AUTH_USER_MODEL= "users.UserProfile"#替换系统用户

# LOCATION = {'安徽省': ['安庆市', '安庆市', '蚌埠市', '巢湖市', '池州市', '滁州市', '阜阳市', '合肥市', '淮北市', '淮南市', '黄山市', '六安市', '马鞍山市', '宿州市', '铜陵市', '芜湖市', '宣城市', '亳州市'], '北京市': ['市辖区', '县'], '福建省': ['福州市', '龙岩市', '南平市', '宁德市', '莆田市', '泉州市', '三明市', '厦门市', '漳州市'], '甘肃省': ['白银市', '定西市', '甘南藏族自治州', '嘉峪关市', '金昌市', '酒泉市', '兰州市', '临夏回族自治州', '陇南市', '平凉市', '庆阳市', '天水市', '武威市', '张掖市'], '广东省': ['潮州市', '东莞市', '佛山市', '广州市', '河源市', '惠州市', '江门市', '揭阳市', '茂名市', '梅州市', '清远市', '汕头市', '汕尾市', '韶关市', '深圳市', '阳江市', '云浮市', '湛江市', '肇庆市', '中山市', '珠海市'], '广西壮族自治区': ['百色市', '北海市', '崇左市', '防城港市', '桂林市', '贵港市', '河池市', '贺州市', '来宾市', '柳州市', '南宁市', '钦州市', '梧州市', '玉林市'], '贵州省': ['安顺市', '毕节地区', '贵阳市', '六盘水市', '黔东南苗族侗族自治州', '黔南布依族苗族自治州', '黔西南布依族苗族自治州', '铜仁地区', '遵义市'], '海南省': ['海口市', '三亚市', '省直辖县级行政单位'], '河北省': ['保定市', '沧州市', '承德市', '邯郸市', '衡水市', '廊坊市', '秦皇岛市', '石家庄市', '唐山市', '邢台市', '张家口市'], '河南省': ['安阳市', '鹤壁市', '焦作市', '开封市', '洛阳市', '南阳市', '平顶山市', '三门峡市', '商丘市', '新乡市', '信阳市', '许昌市', '郑州市', '周口市', '驻马店市', '漯河市', '濮阳市'], '黑龙江省': ['大庆市', '大兴安岭地区', '哈尔滨市', '鹤岗市', '黑河市', '鸡西市', '佳木斯市', '牡丹江市', '七台河市', '齐齐哈尔市', '双鸭山市', '绥化市', '伊春市'], '湖北省': ['鄂州市', '恩施土家族苗族自治州', '黄冈市', '黄石市', '荆门市', '荆州市', '省直辖行政单位', '十堰市', '随州市', '武汉市', '咸宁市', '襄樊市', '孝感市', '宜昌市'], '湖南省': ['常德市', '长沙市', '郴州市', '衡阳市', '怀化市', '娄底市', '邵阳市', '湘潭市', '湘西土家族苗族自治州', '益阳市', '永州市', '岳阳市', '张家界市', '株洲市'], '吉林省': ['白城市', '白山市', '长春市', '吉林市', '辽源市', '四平市', '松原市', '通化市', '延边朝鲜族自治州'], '江苏省': ['常州市', '淮安市', '连云港市', '南京市', '南通市', '苏州市', '宿迁市', '泰州市', '无锡市', '徐州市', '盐城市', '扬州市', '镇江市'], '江西省': ['抚州市', '赣州市', '吉安市', '景德镇市', '九江市', '南昌市', '萍乡市', '上饶市', '新余市', '宜春市', '鹰潭市'], '辽宁省': ['鞍山市', '本溪市', '朝阳市', '大连市', '丹东市', '抚顺市', '阜新市', '葫芦岛市', '锦州市', '辽阳市', '盘锦市', '沈阳市', '铁岭市', '营口市'], '内蒙古自治区': ['阿拉善盟', '巴彦淖尔市', '包头市', '赤峰市', '鄂尔多斯市', '呼和浩特市', '呼伦贝尔市', '通辽市', '乌海市', '乌兰察布市', '锡林郭勒盟', '兴安盟'], '宁夏回族自治区': ['固原市', '石嘴山市', '吴忠市', '银川市', '中卫市'], '青海省': ['果洛藏族自治州', '海北藏族自治州', '海东地区', '海南藏族自治州', '海西蒙古族藏族自治州', '黄南藏族自治州', '西宁市', '玉树藏族自治州'], '山东省': ['滨州市', '德州市', '东营市', '菏泽市', '济南市', '济宁市', '莱芜市', '聊城市', '临沂市', '青岛市', '日照市', '泰安市', '威海市', '潍坊市', '烟台市', '枣庄市', '淄博市'], '山西省': ['长治市', '大同市', '晋城市', '晋中市', '临汾市', '吕梁市', '朔州市', '太原市', '忻州市', '阳泉市', '运城市'], '陕西省': ['安康市', '宝鸡市', '汉中市', '商洛市', '铜川市', '渭南市', '西安市', '咸阳市', '延安市', '榆林市'], '上海市': ['市辖区', '县'], '四川省': ['阿坝藏族羌族自治州', '巴中市', '成都市', '达州市', '德阳市', '甘孜藏族自治州', '广安市', '广元市', '乐山市', '凉山彝族自治州', '眉山市', '绵阳市', '南充市', '内江市', '攀枝花市', '遂宁市', '雅安市', '宜宾市', '资阳市', '自贡市', '泸州市'], '天津市': ['市辖区', '县'], '西藏自治区': ['阿里地区', '昌都地区', '拉萨市', '林芝地区', '那曲地区', '日喀则地区', '山南地区'], '新疆维吾尔自治区': ['阿克苏地区', '阿勒泰地区', '巴音郭楞蒙古自治州', '博尔塔拉蒙古自治州', '昌吉回族自治州', '哈密地区', '和田地区', '喀什地区', '克拉玛依市', '克孜勒苏柯尔克孜自治州', '省直辖行政单位', '石河子市', '塔城地区', '吐鲁番地区', '乌鲁木齐市', '伊犁哈萨克自治州'], '云南省': ['保山市', '楚雄彝族自治州', '大理白族自治州', '德宏傣族景颇族自治州', '迪庆藏族自治州', '红河哈尼族彝族自治州', '昆明市', '丽江市', '临沧市', '怒江傈僳族自治州', '曲靖市', '思茅市', '文山壮族苗族自治州', '西双版纳傣族自治州', '玉溪市', '昭通市'], '浙江省': ['杭州市', '湖州市', '嘉兴市', '金华市', '丽水市', '宁波市', '绍兴市', '台州市', '温州市', '舟山市', '衢州市'], '重庆市': ['市辖区', '县']}


#发送邮件配置
EMAIL_HOST = 'smtp.qq.com'
EMAIL_POSRT = 25
EMAIL_HOST_USER = "1194380923@qq.com"#邮箱名
EMAIL_HOST_PASSWORD = "xpkdjgkhhwvbgjce"#密码，这里要换成授权码
EMAIL_USE_TLS = False
EMAIL_FROM = "1194380923@qq.com"#邮箱名


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$|^177\d{8}$"

#云片网设置
APIKEY = '7d850770e04e8ba10d9a93f4b8f77528'

from datetime import datetime,timedelta
# 与drf的jwt相关的设置
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': timedelta(days=10),#设置JWT过期时间
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_RESPONSE_PAYLOAD_HANDLER':'utils.helper.jwt_response_payload_handler',
}


# 设置邮箱和用户名和手机号均可登录
AUTHENTICATION_BACKENDS = (
    'utils.helper.CustomBackend',#自定义登陆的是用户名和邮箱均可
    # 'social_core.backends.weibo.WeiboOAuth2',
    # 'social_core.backends.qq.QQOAuth2',
    # 'social_core.backends.weixin.WeixinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)







