# Generated by Django 2.2.14 on 2020-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRISPR',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='PK')),
                ('CRISPR_Consensus', models.TextField(blank=True, null=True, verbose_name='CRISPR 序列')),
                ('CRISPR_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRISPR 名字')),
                ('CRISPR_Length', models.IntegerField(blank=True, null=True, verbose_name='the length of CRISPR')),
                ('Organism', models.CharField(blank=True, max_length=100, null=True, verbose_name='the source of bacterial')),
                ('CRISPR_type', models.CharField(blank=True, choices=[('I', '第一种类型'), ('II', '第二种类型'), ('III', '第三种类型'), ('IV', '第四种类型'), ('V', '第五种类型'), ('VI', '第六种类型'), ('VII', '第七种类型'), ('VIII', '第八种类型'), ('IX', '第九种类型'), ('X', '第十种类型')], max_length=50, null=True, verbose_name='CRISPR types ')),
                ('PI_Sequence', models.TextField(blank=True, null=True, verbose_name='PI sequences')),
                ('PI_Length', models.IntegerField(blank=True, null=True, verbose_name='the length of PI')),
                ('PI_Start_Position', models.IntegerField(blank=True, null=True, verbose_name='the start position of PI_sequences in CRISPR_sequence')),
                ('PAM_Consensus', models.CharField(blank=True, max_length=50, null=True, verbose_name='PAM 序列')),
                ('PAM_Length', models.IntegerField(blank=True, null=True, verbose_name='the length of PAM')),
            ],
        ),
    ]
